name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4

      # Configuração do JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Identificador do servidor usado no settings.xml
          settings-path: ${{ github.workspace }}/.github # Local onde o settings.xml está armazenado

      # Configuração do arquivo settings.xml
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cp .github/settings.xml ~/.m2/settings.xml

      # Compilar o projeto com Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Publicar no GitHub Packages
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s ~/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
